deployment = "deployment.toml"

[[contracts]]
name = "state-validator"
template_type = "Rust"

[[contracts]]
name = "deposition-lock"
template_type = "Rust"

# [mapping_dirs]
# "../types" = "/code/types"