version = "0.3.0 1d5e383"
deployment = "deployment.toml"
[rust]
workspace_dir = "contracts"

[[contracts]]
name = "state-validator"
template_type = "Rust"

[[contracts]]
name = "deposition-lock"
template_type = "Rust"
