version = "0.4.1 "
deployment = "deployment.toml"
[rust]
workspace_dir = "contracts"

[[contracts]]
name = "state-validator"
template_type = "Rust"

[[contracts]]
name = "deposition-lock"
template_type = "Rust"
