[workspace]
members = [
  "crates/chain",
  "crates/config",
  "crates/common",
  "crates/generator",
  "crates/traits",
  "crates/db",
  "crates/store",
  "crates/types",
  "crates/jsonrpc-types",
  "packages/godwoken/native",
]
