[package]
name = "gw-setup-tool"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
anyhow = "1.0"
faster-hex = "0.4.1"
toml = "0.5"
gw-config = { path = "../config" }
gw-common = { path = "../common" }
gw-jsonrpc-types = { path = "../jsonrpc-types" }
