[package]
name = "gw-store"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-types = { path = "../types" }
gw-common = { path = "../common" }
gw-generator = { path = "../generator" }
ckb-types = "0.37.0"
anyhow = "1.0"
parking_lot = "0.11"