[package]
name = "gw-block-producer"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-common = { path = "../common" }
gw-types = { path = "../types" }
gw-store = { path = "../store" }
gw-generator = { path = "../generator" }
anyhow = "1.0"
