[package]
name = "gw-block-producer"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-common = { path = "../common" }
gw-config = { path = "../config" }
gw-chain = { path = "../chain" }
gw-types = { path = "../types" }
gw-store = { path = "../store" }
gw-generator = { path = "../generator" }
gw-mem-pool = { path = "../mem-pool" }
faster-hex = "0.4"
ckb-crypto = "0.37.0"
toml = "0.5"
parking_lot = "0.11"
anyhow = "1.0"
