name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Rust components
      run: rustup component add rustfmt && rustup component add clippy
    - name: Install moleculec
      run: cargo install moleculec --version 0.6.1
    - name: Check format
      run: cargo fmt -- --check
