name: Test

on:
  push:
    branches:
    # - main
    - CI
    # - dependabot/**
  pull_request:
    branches:
    - develop

jobs:
  devnet:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Cache Rust - Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Install moleculec
      run: |
        test "$(moleculec --version)" = "Moleculec 0.6.1" \
        || CARGO_TARGET_DIR=target/ cargo install moleculec --version 0.6.1

    - name: Godwoken Kicker services
      run: |
        docker-compose --version
        cd kicker
        make init
        make start
  
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    # - name: Install node
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 14.x

    # - name: Run tests
    #   run: 

    # - name: Stop containers
    #   if: always()
    #   run: docker-compose -f "docker-compose.yml" down
