name: Test

on:
  push:
    branches:
    # - main
    - CI
    # - dependabot/**
  pull_request:
    branches:
    - develop

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Start containers
      run: docker-compose --version
    # run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    # - name: Install node
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 14.x

    # - name: Run tests
    #   run: 

    # - name: Stop containers
    #   if: always()
    #   run: docker-compose -f "docker-compose.yml" down
